steps:

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Pipeline triggered successfully!"

      FILES=$$(git show --name-only --pretty="" $COMMIT_SHA)

      echo "Changed files:"
      echo "$$FILES"

      for FILE in $$FILES; do

        if [ ! -f "$$FILE" ]; then
          continue
        fi

        SIZE=$$(stat -c%s "$$FILE")

        echo "----------------------"
        echo "File: $$FILE"
        echo "Size: $$SIZE bytes"

        if [ $$SIZE -lt 1000 ]; then
          echo "Action: SMALL file detected"
        elif [ $$SIZE -lt 1000000 ]; then
          echo "Action: MEDIUM file detected"
        else
          echo "Action: LARGE file detected (future Dataproc trigger)"
        fi

      done

options:
  logging: CLOUD_LOGGING_ONLY
