steps:

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Pipeline triggered successfully!"

      FILE=$$(git show --name-only --pretty="" $COMMIT_SHA | head -1)

      echo "Changed file: $$FILE"

      if [ -z "$$FILE" ]; then
        echo "No file detected"
        exit 0
      fi

      SIZE=$$(stat -c%s "$$FILE")

      echo "File size is $$SIZE"

options:
  logging: CLOUD_LOGGING_ONLY
