steps:

- name: 'ubuntu'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Pipeline triggered successfully!"

      FILE=$(git diff --name-only HEAD~1 HEAD | head -1)

      echo "Changed file: $FILE"

      SIZE=$(stat -c%s "$FILE")

      echo "File size is $SIZE"

options:
  logging: CLOUD_LOGGING_ONLY
